# -*- coding: utf-8 -*-
"""LittleBank_case_study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjCEpiA2Eidhx2_adxLev-6WGm8MQCT_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## 0. Load and Overview the Data"""

df = pd.read_csv("/content/data/PwC_CaseStudy_LittleBank_train.csv").convert_dtypes()

pd.set_option("display.max_columns", None)
df

df["outcome"] = df["outcome"].astype("string")

df.info()

df["outcome"].value_counts()            # From 35000 consumers only 3952 accepted the product, i.e. approx. 10%

df["outcome"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f")
plt.title("Outcome of the Customer's Subscription")
plt.ylabel("")
plt.show()

df["outcome_previous"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f")
plt.title("Previous Outcome of the Customer's Subscription")
plt.ylabel("")
plt.show()

df["job"].value_counts()

df["job"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Job of the Customers")
plt.ylabel("")
plt.show()

df["education"].describe()

df["education"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Education of the Customers")
plt.ylabel("")
plt.show()

# df["num_contacts"].unique()
# df["outcome_previous"].unique()
df["default"].unique()

df["default"].value_counts()    # Default is not adding any value to the analysis;
                                # The Marketing was done only towards new clients

df["outcome_previous"].value_counts()

df["mortgage"].value_counts()

df["contact"].value_counts().plot(kind = "bar", xlabel = "", ylabel = "Number of Contacts",
                                  title = "Type of Communication with Customers",
                                  rot = 0);

"""#### Three Main Observations 📝

1. Of 35000 people, only 3952 subscribed. 31048 people declined the offer. This means that only 11.3% of the people subscribed to the classic savings account. Further, there is a variable for the outcome of previous campaigns. However, 86% of the values do not exist, i.e. more than 30,000 values. Hence, the column will be useless for the analysis.

2. The customers work in various areas. Most of them have administrative, industrial or technical jobs.

3. There are two ways to approach the customers - via mobile or via landline. However, nowadays there are more effective ways to advertise your product. There is one question that bothers me. This comes to my mind looking at the advertising campaign: "Who under the blue skies is using a landline phone nowadays?"

## 1. Cleaning the Data

#### Dataset Overview 📊

> The **number of data entries** is 35000. They could be divided into 5 main groups:
>
> * When a contact was made
> * Contact Info
> * Personal Info of the Customer
> * Environmental parameters
> * Macroeconomic Situation

#### Target Value 🎯
> The last column of the data frame is **the outcome of the contact**. It indicates whether the client has purchased the product or not. This column will be the target of the ML model. Furthermore, the outcome column will be the main part for most of the figures.

#### Hypotheses ⁉️
> A few **hypotheses** should be defined at the beginning of the analysis. It is very likely that the economic factors will influence the outcome of the campaign. In real-world scenarios, the economy directly affects the customer's behaviour. In addition, it is very important to review the marketing campaign and estimate how positive it was. The success of each type of contact should be compared. Lastly, there is a big possibility that the personal status of each customer (age, job, mortgage, marital status, etc) has a key role in the success of the marketing.

#### Day & Month 📅
> There are two very interesting columns for the *month and the day when the contact with the customer was made*. One of the most important analyses will be the outcome of the campaign based on day and month.
"""

df_tr = df.copy()

df_tr.info()

df_tr.loc[df_tr.isna().any(axis = "columns")].count()

df_tr[df_tr.duplicated() == True]

df_tr.head()

df_tr.loc[:, "call_centre_volume":"outcome"].describe()

df_tr["forward_rate"].median()

# Store the file after the data cleaning
#df_tr.to_csv("PwC_CaseStudy_LittleBank_train_cleaned.csv", index=False)

"""## 2. Macroeconomic and Enviromental Factors Analysis"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# df = pd.read_csv("/content/data/PwC_CaseStudy_LittleBank_train.csv").convert_dtypes()

# pd.set_option('display.max_columns', None)
# df

df["outcome"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f")
plt.title("Outcome of the Customer's Subscription")
plt.ylabel("")
plt.show()

df_tr = df.copy()

months_unique = df_tr.month.unique()
days_unique = df_tr.day_of_week.unique()
months_unique, days_unique

days_of_the_week = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
months_in_the_year = ["jan", "feb", "mar", "apr", "may", "jun",
                      "jul", "aug","sep", "oct", "nov", "dec"]

# A dictionary that maps the day with the corresponding number of the day in a week
days_of_the_week_dict = {day:i for i, day in enumerate(days_of_the_week, start = 1)}

# A dictionary that maps the month with the corresponding number of the month in the year
months_in_the_year_dict = {month_str:i for i, month_str in enumerate(months_in_the_year, start = 1)}

#df_tr['month'].map(months_in_the_year_dict)

# Insert a new column in the data frame that maps the months with the corresponding number
df_tr.insert(loc = 2, column = "month_no", value = df_tr['month'].map(months_in_the_year_dict))
#df_tr.insert(loc = 4, column = "day_of_week_no", value = df_tr['day_of_week'].map(days_of_the_week_dict))

df_tr.sort_values(by = "month_no", inplace = True)
df_tr

## Insert a new column in the data frame that maps the days with the corresponding number
#df_tr.insert(loc = 3, column = "day_no", value = df_tr["day_of_week"].map(days_of_the_week_dict))

## Drop the new Column if necessary
#df_tr.drop(labels = "month_no", axis = 1, inplace = True)
#df_tr

df_outcome_true = df_tr[df_tr["outcome"] == "True"]
df_outcome_false = df_tr[df_tr["outcome"] == "False"]

df_tr.info()

columns = [df_tr.columns[0]] + list(df_tr.columns[18:])   #24 with drop /25 with no drop
df_economy = df_tr[columns]

df_economy.describe()

# There is a higher probability that num_employed and price_index do not influence the results
# forward_rate, consumer_confidence and employment_variation have the highest fluctuations

df_economy[df_economy["outcome"] == "True"].describe()

df_economy[df_economy["outcome"] == "False"].describe()

plt.plot(df_tr["month_no"].unique(), df_tr["month_no"].value_counts(sort = False));

plt.title("Number of Calls for each Month")
plt.xlabel("Month")
plt.ylabel("Number of Calls")
plt.xticks(df_tr["month_no"].unique())
plt.show()

df_economy_mean = df_tr.groupby("month_no")[["forward_rate", "num_employed",
                                               "consumer_confidence", "price_index",
                                               "employment_variation"]].agg("mean")     # median
df_economy_mean

df_economy_mean_true = df_outcome_true.groupby("month_no")[["forward_rate", "num_employed",
                                               "consumer_confidence", "price_index",
                                               "employment_variation"]].agg("mean")
df_economy_mean_false = df_outcome_false.groupby("month_no")[["forward_rate", "num_employed",
                                               "consumer_confidence", "price_index",
                                               "employment_variation"]].agg("mean")

months_x_axis = df_tr["month_no"].unique()
months_x_axis

plt.plot(months_x_axis, df_economy_mean["forward_rate"], "b", label = "All Outcomes")
plt.plot(months_x_axis, df_economy_mean_true["forward_rate"], "r", label = "Positive Outcome")
plt.plot(months_x_axis, df_economy_mean_false["forward_rate"], "g", label = "Negative Outcome")

plt.title("Outcome of the Campaign Based on Forward Rate Values")
plt.xlabel("Month")
plt.ylabel("Forward Rate")
plt.xticks(months_x_axis)
plt.legend()
plt.show()

# There is a higher probability that num_employed and price_index do not influence the results
# forward_rate, consumer_confidence and employment_variation have the highest fluctuations

plt.plot(months_x_axis, df_economy_mean["consumer_confidence"], "b", label = "All Outcomes")
plt.plot(months_x_axis, df_economy_mean_true["consumer_confidence"], "r", label = "Positive Outcome")
plt.plot(months_x_axis, df_economy_mean_false["consumer_confidence"], "g", label = "Negative Outcome")

plt.title("Outcome of the Campaign Based on Consumer Confidence")
plt.xlabel("Month")
plt.ylabel("Consumer Confidence")
plt.xticks(months_x_axis)
plt.legend()
plt.show()

plt.plot(months_x_axis, df_economy_mean["employment_variation"], "b", label = "All Outcomes")
plt.plot(months_x_axis, df_economy_mean_true["employment_variation"], "r", label = "Positive Outcome")
plt.plot(months_x_axis, df_economy_mean_false["employment_variation"], "g", label = "Negative Outcome")

plt.title("Outcome of the Campaign Based on the Employment Variation")
plt.xlabel("Month")
plt.ylabel("Employment Variation")
plt.xticks(months_x_axis)
plt.legend()
plt.show()

"""Economy Parameters that aren't supposed to influence highly the outcome of the marketing"""

plt.plot(months_x_axis, df_economy_mean["num_employed"], "b", label = "All Outcomes")
plt.plot(months_x_axis, df_economy_mean_true["num_employed"], "r", label = "Positive Outcome")
plt.plot(months_x_axis, df_economy_mean_false["num_employed"], "g", label = "Negative Outcome")

plt.title("Outcome of the Campaign Based on the Number of Employed People")
plt.xlabel("Month")
plt.ylabel("Number of Employed People")
plt.xticks(months_x_axis)
plt.legend()
plt.show()

plt.plot(months_x_axis, df_economy_mean["price_index"], "b", label = "All Outcomes")
plt.plot(months_x_axis, df_economy_mean_true["price_index"], "r", label = "Positive Outcome")
plt.plot(months_x_axis, df_economy_mean_false["price_index"], "g", label = "Negative Outcome")

plt.title("Outcome of the Campaign Based on the Price Index")
plt.xlabel("Month")
plt.ylabel("Price Index")
plt.xticks(months_x_axis)
plt.legend()
plt.show()

"""> The figures are not quite informative. Most of the section will be deleted in the final solution.

## 3. Analyze the Influence of Day and Months Over the Outcome

This is the most important analysis. It should be done first. Don't forget that in data science tasks, the main goals are to understand the data and make the right conclusions.
"""

df_outcome_pivot = df_tr.pivot_table(index = "month",
                                     columns = "outcome",
                                     aggfunc = "size",
                                     sort = False)
df_outcome_pivot["Total"] = df_outcome_pivot.iloc[:, 0] + df_outcome_pivot.iloc[:, 1]
df_outcome_pivot["Successful_Rate"] = (df_outcome_pivot.iloc[:, 0] / df_outcome_pivot.iloc[:, 2]) * 100

df_outcome_pivot
# Total Column, Percent of Successful Outcomes
# Day and Months Connected To the Successfull Outcome

df_outcome_pivot.iloc[:, 0:3].plot(kind = "bar", figsize = (10, 8), rot = 45)

plt.xlabel("Month")
plt.ylabel("Number of Subscriptions")
plt.title("Success of the Marketing Campaign by Months")
plt.show()

df_outcome_pivot.iloc[:, 3].plot(kind = "line")

label_month = df_outcome_pivot.index
index_month = range(len(label_month))

plt.xlabel("Month")
plt.xticks(index_month, label_month)
plt.ylabel("Succesful Rate (%)")
plt.title("Percentage of Possitive Outcomes by Months")

ax = plt.gca()
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f"{int(y)}%"))

"""Days..."""

df_tr.insert(loc = 4, column = "day_of_week_no", value = df_tr['day_of_week'].map(days_of_the_week_dict))

df_tr.sort_values(by = ["month_no", "day_of_week_no"], inplace = True)
df_tr

df_tr_days = df_tr.groupby(["month", "day_of_week"], sort = False)["outcome"].agg("size")
df_tr_days

df_tr_days_pivot = df_tr.pivot_table(index = ["month", "day_of_week"],
                                     columns = "outcome",
                                     aggfunc = "size",
                                     sort = False)
df_tr_days_pivot

df_tr_days_pivot["Total"] = df_tr_days_pivot.iloc[:, 0] + df_tr_days_pivot.iloc[:, 1]
df_tr_days_pivot

df_tr_days_pivot.iloc[0:5, :]

df_tr_days_pivot.iloc[:, 0:3].values

#days_of_the_week = ["mon", "tue", "wed", "thu", "fri"]
months_in_the_year_df = ["mar", "apr", "may", "jun",
                      "jul", "aug","sep", "oct", "nov", "dec"]

df_tr_days_pivot.loc["dec"].columns
#df_tr_days_pivot.loc["dec"].plot(kind = "bar")

## View the dataframes
#df_plot

#pd.set_option('display.max_rows', None)
#pd.reset_option("display.max_rows")

#df_melted

df_plot = df_tr_days_pivot.reset_index()
df_melted = df_plot.melt(id_vars = ['month', 'day_of_week'],
                         value_vars = ["True", "False", 'Total'],
                         var_name = 'outcome_type',
                         value_name = 'outcome_count')

total_months_df = len(months_in_the_year_df)
rows = int(total_months_df / 2)
cols = 2
y_axis_max_value = df_plot["Total"].max() # Possible scaling 1.05 * df_plot["Total"].max()

fig, ax = plt.subplots(rows, cols, figsize = (15, 21))
sns.set_theme(style = "ticks")
#sns.set_palette("tab10")

for i, month in enumerate(months_in_the_year_df):
    row_idx = i // cols
    col_idx = i % cols
    current_month_df = df_melted[df_melted['month'] == month]

    sns.barplot(data = current_month_df,
                x = 'day_of_week',
                y = 'outcome_count',
                hue = 'outcome_type',
                palette = "tab10",
                ax = ax[row_idx, col_idx])

    ax[row_idx, col_idx].set_title(f"Subscriptions for {month.capitalize()}")
    ax[row_idx, col_idx].set_ylabel("Number of Subscriptions")
    ax[row_idx, col_idx].set_xlabel("Day of Week")
    ax[row_idx, col_idx].tick_params(axis = 'x', rotation = 45)
    ax[row_idx, col_idx].legend(title = 'Outcome')


plt.tight_layout()
plt.show()

df_plot.plot(kind = "line",
             title = "The Outcome of the Advertisement Campaign",
             xticks = [],
             xlabel = "Days of the Months",
             ylabel = "Outcome Count");
# The advertisement campaign was a total failure...

"""😥😥😫

> The marketing campaign was a total failure. The first and the last figures show that the subscriptions do not increase, even though thousands of contacts were made. For May, the savings account product was advertised to 11721 people. Only 749 of them have subscribed. This is exactly 6.39%. That's a disaster.

> When we compare the results of the campaign by days of each month, the conclusion is the same - the marketing was a total failure. There are days when the success rate is above 50%, but a small number of people subscribed in absolute terms. The hypothesis that there is a day in the month when the subscription rate is relatively high could not be accepted.

> Lets compare the positive outcomes with the total number of calls. In March, September, October and December, there is the highest percentage of successful outcomes. In March, more than half of the customers subscribed to the product (50.64%). However, in these months the marketing campaign was not very persuasive.

## 4. Marketing Campaign Analysis
"""

df_tr.info()

df["contact"].value_counts().plot(kind = "bar", xlabel = "", ylabel = "Number of Contacts",
                                  title = "Type of Communication with Customers",
                                  rot = 0);

sns.boxplot(data = df_tr, x = "num_contacts", y = "outcome")
sns.set_theme(style="ticks")

# this is all the same
plt.title("The Number of Contacts and the Corresponding Outcome")
plt.xlabel("Number of Contacts")
plt.ylabel("Outcome of the Contact")

plt.xlim(0, 45)

plt.show()

df["num_contacts"].sort_values(ascending = False).head(15)  # 30-56 calls for one offer for the same person ???
#df["num_contacts"].sort_values(ascending = False).value_counts(sort = False).head(30) # The Marketing is Total Failure;

# It is very likely that the data is generated by AI; There isn't any logic to make 56 contacts for 1 person for marketing.
# Guess what present you will receive from me when call me for 4th time to promote me your product...

df_tr.loc[:, "contact":"outcome_previous"].describe()

df_tr.loc[:, "call_centre_volume"].describe()

len(df_tr[df_tr["days_since_previous"].values == -1])

len(df_tr[df_tr["num_contacts_previous"].values == 0])

df["outcome_previous"].unique()

df["outcome_previous"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f")
plt.title("Previous Outcome of the Customer's Subscription")
plt.ylabel("")
plt.show()

# Successful outcome by month (day) for a type of contact

df_contact = df_tr.pivot_table(index = "contact",
                               columns = "outcome",
                               aggfunc = "size",
                               sort = False)

type_of_contact_subscription = (df_contact.iloc[:, 0] / df_contact.iloc[:, 1]) * 100 # in percentage
type_of_contact_subscription

df_contact.plot(kind = "bar", xlabel = "Type of contact", ylabel = "Outcome",
                title = "Outcome of the Marketing", rot = 45);

mean_contacts_successful_outcome = df_tr[df_tr["outcome"] == "True"]["num_contacts"].mean()     # 2.045
num_contacts_successful_outcome = df_tr[df_tr["outcome"] == "True"]["num_contacts"].median()    # 2.0

print(f"The average number of contacts for a successful outcome is {int(num_contacts_successful_outcome)}.")

df_contact_type_pivot = df_tr.pivot_table(index = ["month", "contact"],
                                          columns = "outcome",
                                          aggfunc = "size",
                                          sort = False)
df_contact_type_pivot["Total"] = df_contact_type_pivot.iloc[:, 0] + df_contact_type_pivot.iloc[:, 1]
df_contact_type_pivot

df_plot_contact = df_contact_type_pivot.reset_index()
df_melted = df_plot_contact.melt(id_vars = ['month', 'contact'],
                                 value_vars = ["True", "False", 'Total'],
                                 var_name = 'outcome_type',
                                 value_name = 'outcome_count')

total_months_df = len(months_in_the_year_df)
rows = int(total_months_df / 2)
cols = 2
y_axis_max_value = df_plot_contact["Total"].max() #+ 1.05 * df_plot["Total"].max()

fig, ax = plt.subplots(rows, cols, figsize = (15, 21))
sns.set_theme(style = "ticks")
#sns.set_palette("tab10")

for i, month in enumerate(months_in_the_year_df):
    row_idx = i // cols
    col_idx = i % cols
    current_month_df = df_melted[df_melted["month"] == month]

    sns.barplot(data = current_month_df,
                x = "contact",
                y = "outcome_count",
                hue = "outcome_type",
                palette = "tab10",
                ax = ax[row_idx, col_idx])

    ax[row_idx, col_idx].set_title(f"Subscriptions for {month.capitalize()}")
    ax[row_idx, col_idx].set_ylabel("Number of Subscriptions")
    ax[row_idx, col_idx].set_xlabel("")
    ax[row_idx, col_idx].tick_params(axis = "x", rotation = 45)
    ax[row_idx, col_idx].legend(title = "Outcome")

plt.tight_layout()
plt.show()

df_tr["days_since_previous"].value_counts()
df_days_previous = df_tr[(df_tr["days_since_previous"] >= 0) & (df_tr["outcome"] == "True")]
df_days_previous

df_days_previous[["days_since_previous", "num_contacts_previous", "call_centre_volume"]].describe()

df_days_previous.groupby("contact")[["days_since_previous", "call_centre_volume", "num_contacts"]].agg(["mean", "median"])

df_tr.groupby(["month", "outcome"], sort = False)["call_centre_volume"].agg("median")

"""#### Overview of the Marketing Campaign 📊
> The classic savings account was advertised through a call. The clients were contacted on mobile (22215 calls) or on their landline (12785 calls). There are strange outliers in the data. There are a few people whom we called 56 times, 43 times, 42 times, etc. If someone dares to think of calling me 56 times to advertise his bloody product, he would receive a warm and energetic blessing after the third call. And that lucky number will be added to my "forever after happy block list" for eternity.

#### Nonexistent Variable ❌
> In addition, most of the values of the days_since_previous column are nonexistent. The same could be said about the outcome_previous column. The mean number of contacts for a successful call is 2.

#### Successful Calls ✅
> The second call for the successful outcome was made around 6 days after the first call. Hence, to increase the chances of success, the second call should be made around 6 days after the first call. In addition,
It is very possible that the volume of the call centre does not affect the success of the call.

#### Marketing in the Digital Era 💬
> As it could be expected, most of the subscriptions came from a mobile device. This is true for each month. Nevertheless, in the digital era where everyone has a profile in more than one social network, there are certainly better ways to connect with your potential customers.

## 5. Analysis Based on the Personal Info of the Customers
"""

df["job"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Job of the Customers")
plt.ylabel("")
plt.show()

df_jobs_pivot = df_tr.pivot_table(index = "job",
                                  columns = "outcome",
                                  aggfunc = "size")

df_jobs_pivot["Total"] = df_jobs_pivot["False"] + df_jobs_pivot["True"]
df_jobs_pivot["Successful_Rate"] = (df_jobs_pivot["True"] / df_jobs_pivot["False"]) * 100
df_jobs_pivot

df_jobs_pivot["Successful_Rate"].values

x = df_jobs_pivot.index
y = df_jobs_pivot["Successful_Rate"].values

y1 = np.ones(len(y)) * 15              # Draw a line for 15%

plt.figure(figsize = (12, 10))
plt.plot(x, y, color = "green", marker = "o", linestyle = "dashed", dash_capstyle = "butt",
         gapcolor = "orange")
plt.plot(x, y1, color = "red", linewidth = 2, linestyle = "dashed")

plt.title("Subscriptions by Profession of the Customers")
plt.xlabel("Jobs of Customers")
plt.xticks(rotation = 45, ha = "center")

plt.ylabel("Success Rate")

ax = plt.gca()
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f"{int(x)}%"))

plt.show()

df_jobs_outcome_t = df_tr[df_tr["outcome"] == "True"].pivot_table(values = "outcome",
                                                                  index = "job",
                                                                  columns = "contact",
                                                                  aggfunc = "size")
df_jobs_outcome_f = df_tr[df_tr["outcome"] == "False"].pivot_table(values = "outcome",
                                                                   index = "job",
                                                                   columns = "contact",
                                                                   aggfunc = "size")
df_jobs_outcome = df_tr.pivot_table(values = "outcome",
                                    index = "job",
                                    columns = "contact",
                                    aggfunc = "size")

fig, ax = plt.subplots(3, 1, figsize = (12, 16))

df_jobs_outcome_t.plot(kind = "bar", ax = ax[0], rot = 45,
                       colormap = "Spectral")
ax[0].set_title("Positive Outcome and the Type of Contact")
ax[0].set_xlabel("Jobs")
ax[0].set_ylabel("Number of Contacts")

df_jobs_outcome_f.plot(kind = "bar", ax = ax[1], rot = 45,
                       colormap = "Spectral")
ax[1].set_title("Negative Outcome and the Type of Contact")
ax[1].set_xlabel("Jobs")
ax[1].set_ylabel("Number of Contacts")

df_jobs_outcome.plot(kind = "bar", ax = ax[2], rot = 45,
                     colormap = "Spectral")
ax[2].set_title("Type of Contact for Customer's Job")
ax[2].set_xlabel("Jobs")
ax[2].set_ylabel("Number of Contacts")

fig.tight_layout()

df_education = df_tr.pivot_table(index = "education",
                                 columns = "outcome",
                                 aggfunc = "size",
                                 sort = False)

df_education.drop(index="none", inplace=True)

df_education.sort_values(by = "education", inplace = True)

df_education

#df_education = df_education.reset_index()
# df_education_plot = df_education.melt(id_vars = ['education', 'contact'],
#                                       value_vars = ["True", "False"],
#                                       var_name = 'outcome_type',
#                                       value_name = 'outcome_count')
# df_education_plot

df_education.plot(kind = "bar", rot = 45, figsize = (12, 10), colormap = "Spectral",
                  xlabel = "Education", ylabel = "Outcome of the contact",
                  title = "Outcome of the Contact based on Education");

df_age = df_tr[df_tr["age"] < 70]                # The Number of Customers above 70 is small and can be omited
age_unique = df_age["age"].unique().tolist()
age_unique.sort()
#print(age_unique)

age_counts = df_age["age"].value_counts().sort_index()

df_age_true = df_outcome_true[df_outcome_true["age"] < 70]                # The Number of Customers above 70 is small and can be omited
age_unique_true = df_age_true["age"].unique().tolist()
age_unique_true.sort()
#print(age_unique_true)

age_counts_true = df_age_true["age"].value_counts().sort_index()

plt.plot(age_unique, age_counts, "g")
plt.plot(age_unique_true, age_counts_true, "b")

plt.title("Number of Customers by Age")
plt.xlabel("Age of Customers")
plt.ylabel("Number of Customers")
plt.legend(["All Customers", "Positive Outcome"])
#plt.xticks(df_tr["month_no"].unique())
plt.show()

labels = df_tr["marital"].unique()

df_tr["marital"].value_counts().plot(kind = "pie", ylabel = "", labels = labels,
                                     textprops = {"ha": "left", "va": "center"},
                                     labeldistance = 1.15, title = "Marital Status of Clients");

df_tr["mortgage"].value_counts().plot(kind = "pie", startangle = -5, ylabel = "",
                                      title = "Mortgage Status of Clients");

df_tr["personal_loan"].value_counts().plot(kind = "pie", ylabel = "",
                                           title = "Personal Loan Status of Clients");

clients_with_mortgage = len(df_outcome_true[df_outcome_true["mortgage"] == "yes"])
clients_with_loan = len(df_outcome_true[df_outcome_true["personal_loan"] == "yes"])
clients_true_total = len(df_outcome_true)

clients_with_mortgage, clients_with_loan, clients_true_total

fig, ax = plt.subplots(figsize = (8, 6))

personal_info = ["mortgage", "mortgage_total", "personal_loan", "personal_loan_total"]
counts = [clients_with_mortgage, clients_true_total, clients_with_loan, clients_true_total]
bar_labels = ['With Mortgage', 'Total', 'With Personal Loan', 'Total']
bar_colors = ['red', 'green', 'darkorchid', 'green']

ax.bar(personal_info, counts, label = bar_labels, color = bar_colors)

ax.set_xlabel("Personal Info")
ax.set_ylabel("Counts")
ax.set_title("Subscription for the Product based on Personal Information")
ax.legend(title = 'Personal Info')

plt.show()

marital_unknown = df_tr[df_tr["marital"] == "unknown"]
df_marital = df_tr.drop(index = marital_unknown.index)

df_marital_pivot = df_marital.pivot_table(index = "marital",
                                          columns = "outcome",
                                          aggfunc = "size",
                                          sort = False)

df_marital_pivot["Total"] = df_marital_pivot.iloc[:, 0] + df_marital_pivot.iloc[:, 1]

df_marital_pivot

df_marital_pivot.plot(kind = "bar", rot = 45, figsize = (12, 10),
                      xlabel = "Marital Status", ylabel = "Outcome of the Contact",
                      title = "Outcome of the Contact based on Marital Status");

"""#### Job of Customers 🛠️
> Most of the people with a classic savings account have an administrative or technical job. Let's set a 15% treshold for the success rate. The success rate is the ratio of the successful outcomes of a call and the total calls. People who have an administrative job are above the threshold. We could add to them the people who retired, unemployed people and people who participate in full-time education. The product is not so attractive to customers working in other areas. A survey should be made amongst the customers, in order to understand how to improve the product.

#### Type of Contact and Outcome of the Contact ☎️
> The relation between the type of contact and the positive outcome was analysed. Figures proved one more time the point that mobile calls lead to more subscriptions, compared to landline phones.

#### Personal Info of Customers Bonus Analysis 👦🏽
> Most of the customers have a high school education or a university degree. In addition, marketing was focused on people between the ages of 20 and 60. More than half of the people who subscribed for the product also have a mortgage (2133 out of 3952). On the other hand, only 573 out of 3952 have a personal loan in the bank. Lastly, a connection between the marital status and the positive outcome wasn't found

## 6. Analysis Based on the Jobs of the Customers
"""

df_tr.info()

#df_tr.groupby("outcome")[["num_contacts", "days_since_previous", "num_contacts_previous", "call_centre_volume"]].agg(["median", "min", "max"])

df_outcome_true = df_tr[df_tr["outcome"] == "True"]
df_outcome_false = df_tr[df_tr["outcome"] == "False"]

df_jobs_count = df["job"].value_counts()
df_outcome_true_jobs_count = df_outcome_true["job"].value_counts()
df_outcome_false_jobs_count = df_outcome_false["job"].value_counts()

plt.bar(df_jobs_count.index, df_jobs_count)
plt.title("Jobs of the customers")
plt.ylabel("The count of jobs")
plt.xticks(rotation = 45, ha = "right")
plt.show()

fig, ax = plt.subplots(1, 2, figsize = (14, 7))

ax[0].barh(df_outcome_true_jobs_count.index, df_outcome_true_jobs_count)
ax[1].barh(df_outcome_false_jobs_count.index, df_outcome_false_jobs_count)

plt.show()

df_outcome_true_pivot_fr = df_outcome_true.pivot_table(values = "forward_rate",
                                                       index = "job",
                                                       columns = "education",
                                                       aggfunc = "median")
df_outcome_true_pivot_fr.sample(10)

df_outcome_false_pivot = df_outcome_false.pivot_table(values = "forward_rate",
                                                      index = "job",
                                                      columns = "education",
                                                      aggfunc = "median")
df_outcome_false_pivot.sample(10)

df_outcome_true_pivot_fr = df_outcome_true.pivot_table(values = "forward_rate",
                                                       index = "job",
                                                       columns = "personal_loan",
                                                       aggfunc = "median")
df_outcome_true_pivot_fr.sample(10)

df_outcome_false_pivot = df_outcome_false.pivot_table(values = "forward_rate",
                                                      index = "job",
                                                      columns = "education",
                                                      aggfunc = "median")