# -*- coding: utf-8 -*-
"""LittleBank_Case_Study_ML_Concise_Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MvP7AgRWbAks_-8vtZRH6bMeUABdJizO

> This is the concise solution of Task 2 from the LittleBank Case Study. The Detailed Solution could be found in `LittleBank_Case_Study_ML` file. The concise solution is the best choice for the real-time interview.

> PS. Section 7 could also be ommited.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

"""## 0. Load and Overview the Data

>The section is exactly the same as the `0. section` for the EDA solution (task 1).
"""

df = pd.read_csv("/content/data/LittleBank_Case_Study.csv")

pd.set_option("display.max_columns", None)
df

df["outcome"] = df["outcome"].astype("string")

df.info()

df["outcome"].value_counts()            # From 35000 consumers only 3952 accepted the product, i.e. approx. 10%

df["outcome"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f")
plt.title("Outcome of the Customer's Subscription")
plt.ylabel("")
plt.show()

df["outcome_previous"].value_counts().plot(kind = "pie", startangle = 90, autopct = "%1.2f")
plt.title("Previous Outcome of the Customer's Subscription")
plt.ylabel("")
plt.show()

df["job"].value_counts()

df["job"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Job of the Customers")
plt.ylabel("")
plt.show()

df["education"].describe()

df["education"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Education of the Customers")
plt.ylabel("")
plt.show()

df["marital"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Marital Status of the Customers")
plt.ylabel("")
plt.show()

df["mortgage"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Mortgage Status of the Customers")
plt.ylabel("")
plt.show()

df["personal_loan"].value_counts().plot(kind = "pie", autopct = "%1.2f", figsize = (10, 8))
plt.title("Personal Loans of the Customers")
plt.ylabel("")
plt.show()

# df["num_contacts"].unique()
# df["outcome_previous"].unique()
df["default"].unique()

df["default"].value_counts()    # Default is not adding any value to the analysis;
                                # The Marketing was done only towards new clients

df["outcome_previous"].value_counts()

df["mortgage"].value_counts()

df["contact"].value_counts().plot(kind = "bar", xlabel = "", ylabel = "Number of Contacts",
                                  title = "Type of Communication with Customers",
                                  rot = 0);

"""## 1. Cleaning the Data"""

df_tr = df.copy()

"""### 1.1 Remove Duplicates and NaN Values"""

df_tr.info()

df_tr.loc[df_tr.isna().any(axis = "columns")].count()

df_tr[df_tr.duplicated() == True]

df_tr.head()

"""### 1.2 Make Months and Days Column Numerical"""

months_unique = df_tr.month.unique()
days_unique = df_tr.day_of_week.unique()
months_unique, days_unique

days_of_the_week = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
months_in_the_year = ["jan", "feb", "mar", "apr", "may", "jun",
                      "jul", "aug","sep", "oct", "nov", "dec"]

# A dictionary that maps the day with the corresponding number of the day in a week
days_of_the_week_dict = {day:i for i, day in enumerate(days_of_the_week, start = 1)}

# A dictionary that maps the month with the corresponding number of the month in the year
months_in_the_year_dict = {month_str:i for i, month_str in enumerate(months_in_the_year, start = 1)}

#df_tr['month'].map(months_in_the_year_dict)

# Insert a new column in the data frame that maps the months with the corresponding number
df_tr.insert(loc = 2, column = "month_no", value = df_tr['month'].map(months_in_the_year_dict))
df_tr.insert(loc = 4, column = "day_of_week_no", value = df_tr['day_of_week'].map(days_of_the_week_dict))

"""### 1.3 Delete Insignificant Columns and Incorrect Values"""

df_tr.drop(labels = ["month", "day_of_week"], axis = 1, inplace = True)
#df_tr

df_tr.drop(labels = ["days_since_previous", "num_contacts_previous", "default"], axis = 1, inplace = True)

df_tr[df_tr["job"] == "unknown"].index

df_tr.drop(index = (df_tr[df_tr["marital"] == "unknown"]).index, inplace = True)
df_tr.drop(index = (df_tr[df_tr["job"] == "unknown"]).index, inplace = True)
df_tr.drop(index = (df_tr[df_tr["education"] == "unknown"]).index, inplace = True)
df_tr.drop(index = (df_tr[df_tr["mortgage"] == "unknown"]).index, inplace = True)
df_tr.drop(index = (df_tr[df_tr["personal_loan"] == "unknown"]).index, inplace = True)

df_tr.info()

"""### 1.4 Delete Samples that have Extreme Values"""

df_tr.describe().T

df_tr["num_contacts"].plot(kind = "box", vert = False);

df_tr["age"].plot(kind = "box", vert = False);

df_tr = df_tr[(df_tr["num_contacts"] < 10) & (df_tr["age"] < 86)]
df_tr

df_tr.info()

df_tr_sorted = df_tr.sort_values(by = ["month_no", "day_of_week_no"])

# Store the file after the data cleaning
#df_tr.to_csv("LittleBank_Case_Study_Cleaned.csv", index=False)

"""### 1.5 Make Outcome Column Numerical"""

from sklearn.preprocessing import LabelEncoder

target = df_tr["outcome"]

enc_labels = LabelEncoder()
df_tr["outcome_encoded"] = enc_labels.fit_transform(target)

df_tr["outcome_encoded"].value_counts()

"""## 2. Analyze Distribution of Data and Features

### 2.1 Overview Outcome Target Column
"""

df_tr["outcome"].value_counts()

df_tr_day = df_tr_sorted.pivot_table(index = "day_of_week_no",
                                     columns = "outcome",
                                     aggfunc = "size")

df_tr_day.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'], figsize=(10, 6))

plt.xlabel("Days of Week")
plt.ylabel("Outcome of the Campaign")
plt.title("Days of Week vs. Outcome")
plt.xticks(rotation = 0)
plt.show()

df_tr_day = df_tr_sorted.pivot_table(index = "month_no",
                                     columns = "outcome",
                                     aggfunc = "size")

df_tr_day.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'], figsize=(12, 6))

plt.xlabel("Month")
plt.ylabel("Outcome of the Campaign")
plt.title("Month vs. Outcome")
plt.xticks(rotation = 0)
#plt.tight_layout()
plt.show()

df_tr_day = df_tr_sorted.pivot_table(index = "contact",
                                     columns = "outcome",
                                     aggfunc = "size")

df_tr_day.plot(kind = "bar", stacked = True, color=['#5470C6', '#EE6666'])

plt.xlabel("Contact")
plt.ylabel("Outcome of the Campaign")
plt.title("Contact vs. Outcome")
plt.xticks(rotation = 0)
#plt.tight_layout()
plt.show()

"""### 2.2 Correlation"""

df_tr_corr_numerical = df_tr.select_dtypes(include = ["number"]).corr()

fig, ax = plt.subplots(figsize = (15, 15))

sns.heatmap(df_tr_corr_numerical, cmap = "Reds", annot = True, ax = ax)

plt.title("Correlation Matrix")
plt.show()

"""## 3. Train and Test Split

### 3.1 Tackle Data Imbalance

The data for the LittleBank campaign is imbalanced. Near 90% of the data consists of people who didn't subscribe for the savings account. Only 10% of the people accepted the offer and opened a classic savings account. As a result, the smaller class with the people who subscribed will often be misclassified. There is also a bias towards the people who didn't subscribe. To address these problems, a few techniques could be applied:

1. Under-sampling techniques - decrease the number of samples in the majority class

2. Over-sampling - increase the number of samples in the minority class

The most famous sampling techniques are:

* Random Over-Sampling

* SMOTE (Synthetic Minority Over-sampling Technique)

* ADASYN (Adaptive Synthetic Sampling)

The SMOTE technique was implemented in the notebook. It improves the classification of the minority class. Another benefit of SMOTE is the improvement of the ML model's variance. A disadvantage of the approach is the computational cost of the technique. However, in our case, it could be omitted because the data is relatively small.

Feel free to implement the other two over-sampling techniques and observe the result of the ML models. They could lead to better results in other tasks.
"""

from imblearn.over_sampling import SMOTENC

df_tr.columns

input_cols_df = df_tr.columns[:-2]
target_col_df = df_tr.columns[-1]

X = df_tr[input_cols_df].copy()
y = df_tr[target_col_df].copy()

X.shape, y.shape

categorical_cols_df = X.select_dtypes("object").columns.tolist()
categorical_cols_df

smote = SMOTENC(categorical_features = categorical_cols_df, sampling_strategy = "auto", random_state = 42)
X_resampled, y_resampled = smote.fit_resample(X, y)

X_resampled.shape, y_resampled.shape

df_tr_resampled = pd.concat([X_resampled, y_resampled], axis = 1)

df_tr_resampled

"""### 3.2 Split the Data into Train and Test Split"""

train_df, test_df = train_test_split(df_tr_resampled, test_size = 0.2, random_state = 42)

train_df.shape, test_df.shape

df_tr.columns

input_cols = ["month_no", "day_of_week_no", "contact", "num_contacts",
              "age", "marital", "job", "education", "mortgage",
              "personal_loan", "call_centre_volume", "high_temp", "low_temp",
              "forward_rate", "num_employed", "consumer_confidence", "price_index",
              "employment_variation"]
target_col = "outcome_encoded"

train_inputs = train_df[input_cols].copy()
train_targets = train_df[target_col].copy()

test_inputs = test_df[input_cols].copy()
test_targets = test_df[target_col].copy()

numeric_cols = train_inputs.select_dtypes(include = ["number"]).columns.tolist()        # np.number
categorical_cols = train_inputs.select_dtypes("object").columns.tolist()

train_inputs[categorical_cols].nunique()

"""## 4. Pre-processing the Data

### 4.1 Scale
"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(df_tr[numeric_cols])

train_inputs[numeric_cols] = scaler.transform(train_inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_inputs[numeric_cols])

train_inputs.describe()

test_inputs[numeric_cols]

"""### 4.2 Encoding Categorical Data"""

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False, handle_unknown = "ignore")
encoder.fit(df_tr[categorical_cols])

encoder.categories_

train_inputs[categorical_cols].columns

encoded_cols = list(encoder.get_feature_names_out(categorical_cols))

# Remove "." character from the Column Names
trans_table = str.maketrans(".", "_")
encoded_cols = [col.translate(trans_table) for col in encoded_cols]
print(encoded_cols)

train_inputs = pd.concat([train_inputs[numeric_cols], pd.DataFrame(encoder.transform(train_inputs[categorical_cols]), columns=encoded_cols, index=train_inputs.index)], axis=1)
test_inputs = pd.concat([test_inputs[numeric_cols], pd.DataFrame(encoder.transform(test_inputs[categorical_cols]), columns=encoded_cols, index=test_inputs.index)], axis=1)

train_inputs

"""## 5. Save Data Frames"""

import os
from pathlib import Path

save_files_dir = Path("save/")

if save_files_dir.is_dir():
    print(f"The {save_files_dir} directory exists.")
else:
    print(f"{save_files_dir} directory do not exists. Creating one...")
    save_files_dir.mkdir(parents = True, exist_ok = True)
    print(f"{save_files_dir} directory is created.")

train_inputs.to_parquet("save/train_inputs.parquet")
test_inputs.to_parquet("save/test_inputs.parquet")

pd.DataFrame(train_targets).to_parquet("save/train_target.parquet")
pd.DataFrame(test_targets).to_parquet("save/test_target.parquet")

"""## 6. Base Models

### 6.1 Random Guesses and All Negative Models
"""

from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

def random_guess(inputs):
    return np.random.choice([0, 1], len(inputs))

test_acc_random = accuracy_score(test_targets, random_guess(test_inputs))
recall_test_random = recall_score(test_targets, random_guess(test_inputs))
precision_test_random = precision_score(test_targets, random_guess(test_inputs))

print("Metrics to beat...")
print(f"Accuracy = {test_acc_random}, Recall = {recall_test_random}, Precision = {precision_test_random}")

def all_output_negative(inputs):
    return np.full(len(inputs), 0)

accuracy_score(test_targets, all_output_negative(test_inputs))

"""### 6.2 Logistic Regression

#### 6.2.1 Simple Model for Finding the Best Hyperparameters
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import recall_score, precision_score
from sklearn.metrics import precision_recall_fscore_support

model_log_regr_temp = LogisticRegression(C = 0.98, solver = "lbfgs", n_jobs = -1, max_iter = 500)

model_log_regr_temp.fit(train_inputs, train_targets)

train_preds = model_log_regr_temp.predict(train_inputs)
test_preds = model_log_regr_temp.predict(test_inputs)
train_acc = accuracy_score(train_targets, train_preds)
test_acc = accuracy_score(test_targets, test_preds)

precision, recall, f1score, _ = precision_recall_fscore_support(test_targets, test_preds, pos_label = 1, average = "binary")
print(f"Train Accuracy = {train_acc:.5f} Test Accuracy = {test_acc:.5f}, Precision = {precision:.5f}, Recall = {recall:.5f}, F1_Score = {f1score:.5f}")

"""### 6.2.2 Find the Best Parameters via Grid Search"""

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_recall_fscore_support

param_grid = {
    #"penalty": ["elasticnet"],         # "l1", "l2", "elasticnet"
    "C": [0.1, 0.98, 1],                # np.arange(0.01, 1.01, 0.01); np.arange(1, 10.25, 0.25)
    "solver": ["lbfgs"],                # ["lbfgs", "liblinear", "newton-cg", "newton-cholesky", "sag", "saga"],
    "n_jobs": [-1],
    "max_iter": [500],
    #"l1_ratio": np.arange(0, 1.01, 0.01)
}

model_log_regr_simple = LogisticRegression()

grid_search_log_regr = GridSearchCV(estimator = model_log_regr_simple,
                                    param_grid = param_grid,
                                    scoring = ["accuracy", "recall", "precision"],      # Test only one scoring...
                                    n_jobs = -1,
                                    refit = "accuracy",                                 # Accuracy if the classes are balanced, Recall if you use unbalanced data
                                    cv = 5,
                                    verbose = 3)

clf = grid_search_log_regr.fit(train_inputs, train_targets)

clf.best_estimator_

clf.best_params_, clf.best_score_

temp_best_model = clf.best_estimator_
test_preds = temp_best_model.predict(test_inputs)

test_acc = accuracy_score(test_targets, test_preds)

precision, recall, f1score, _ = precision_recall_fscore_support(test_targets, test_preds, pos_label = 1, average = "binary")
print(f"Test Accuracy = {test_acc:.5f}, Precision = {precision:.5f}, Recall = {recall:.5f}, F1_Score = {f1score:.5f}")

## Without Data Resampling
# Train Accuracy: 0.89018    Test Accuracy: 0.89718
# Recall = 0.20546, Precision = 0.59583

## SMOTE Data Resampling
# Train Accuracy = 0.75123, Test Accuracy = 0.76039
# Recall = 0.72394, Precision = 0.77580

"""### 6.3 Bonus Functions"""

def calculate_basic_metrics(targets, preds):
    accuracy = accuracy_score(targets, preds)
    recall = recall_score(targets, preds)#, pos_label = "True")
    precision = precision_score(targets, preds)#, pos_label = "True")

    return accuracy, recall, precision

"""## 7. Lasso and ElasticNet Model

### 7.1 Lasso
"""

#from sklearn.linear_model import LogisticRegression

model_lasso = LogisticRegression(penalty = "l1", C = 1, solver = "saga", n_jobs = -1, max_iter = 500)

model_lasso.fit(train_inputs, train_targets)

train_preds_lasso = model_lasso.predict(train_inputs)
test_preds_lasso = model_lasso.predict(test_inputs)

calculate_basic_metrics(train_targets, train_preds_lasso)

train_acc = accuracy_score(train_targets, train_preds_lasso)
test_acc, recall_test, precision_test = calculate_basic_metrics(test_targets, test_preds_lasso)

print(f"Train Accuracy = {train_acc:.5f}, Test Accuracy = {test_acc:.5f}")
print(f"Recall = {recall_test:.5f}, Precision = {precision_test:.5f}")

## Without Data Resampling
# Train Accuracy = 0.89018, Test Accuracy = 0.89718
# Recall = 0.21408, Precision = 0.59583

## SMOTE Data Resampling
# Train Accuracy = 0.75123, Test Accuracy = 0.76030
# Recall = 0.72231, Precision = 0.77661

"""### 7.2 ElasticNet"""

model_elastic_net = LogisticRegression(penalty = "elasticnet",
                                         C = 1,
                                         solver = "saga",
                                         n_jobs = -1,
                                         max_iter = 500,
                                         l1_ratio = 0.6)

model_elastic_net.fit(train_inputs, train_targets)

train_preds_enet = model_elastic_net.predict(train_inputs)

test_preds_enet = model_elastic_net.predict(test_inputs)

calculate_basic_metrics(train_targets, train_preds_enet)

train_acc = accuracy_score(train_targets, train_preds_enet)
test_acc, recall_test, precision_test = calculate_basic_metrics(test_targets, test_preds_enet)

print(f"Train Accuracy = {train_acc:.5f}, Test Accuracy = {test_acc:.5f}")
print(f"Recall = {recall_test:.5f}, Precision = {precision_test:.5f}")

## Without Data Resampling
# Train Accuracy = 0.89018, Test Accuracy = 0.89718
# Recall = 0.21408, Precision = 0.59583

## SMOTE Data Resampling
# Train Accuracy = 0.75123, Test Accuracy = 0.76021
# Recall = 0.72322, Precision = 0.77593

"""## 8. Decision Tree and Random Forest

### 8.1 Decision Tree

#### 8.1.1 Without Pruning
"""

from sklearn.tree import DecisionTreeClassifier

model_decision_tree = DecisionTreeClassifier(criterion = "gini",
                                             max_depth = 26,           # 15-30  # The Best: 29, 26
                                             min_samples_split = 10,   # 2-15   # The Best: 2, 10
                                             min_samples_leaf = 4,     # 1-15   # The Best: 4
                                             #max_features = ,
                                             max_leaf_nodes = 1300,    # The Best: 1300, 1250, 1500, 2000
                                             random_state = 42)

model_decision_tree.fit(train_inputs, train_targets)

train_preds_dtree = model_decision_tree.predict(train_inputs)
test_preds_dtree = model_decision_tree.predict(test_inputs)

train_acc = accuracy_score(train_targets, train_preds_dtree)
#train_acc  # test_acc = accuracy_score(test_targets, test_preds_dtree)  # test_acc

test_acc, recall_test, precision_test = calculate_basic_metrics(test_targets, test_preds_dtree)

print(f"Train Accuracy = {train_acc:.5f}, Test Accuracy = {test_acc:.5f}")
print(f"Recall = {recall_test:.5f}, Precision = {precision_test:.5f}")

model_decision_tree.tree_.max_depth

model_decision_tree.get_n_leaves()

model_decision_tree.n_features_in_

importance_df = pd.DataFrame({
    "feature": train_inputs.columns,
    "importance": model_decision_tree.feature_importances_
}).sort_values("importance", ascending = False)

importance_df.head(15)

sns.barplot(data = importance_df.head(15), x = "importance", y = "feature",
            hue = "feature", legend = False, palette = "tab10")

plt.title("Feature Importance of the Decision Tree");

## Without Data Resampling
# Train Accuracy = 0.89018, Test Accuracy = 0.89718
# Recall = 0.21408045977011494, Precision = 0.59583

## Overfitted Model (With Smote)
# Train Accuracy = 1.00000, Test Accuracy = 0.81418
# Recall = 0.84354, Precision = 0.77580

## SMOTE Data Resampling
# Train Accuracy = 0.89418, Test Accuracy = 0.83461
# Recall = 0.84824, Precision = 0.82239

"""## 8.2 Random Forest"""

from sklearn.ensemble import RandomForestClassifier

model_random_forest = RandomForestClassifier(n_jobs = -1,
                                             n_estimators = 500,        # 500, 300, 600, 700
                                             max_features = 9,          # 7, 9, 11, 13, 15, 16    The best: 9   Max: 39
                                             max_depth = 35,            # 25, 30, 35
                                             min_samples_split = 2,
                                             random_state = 42)

model_random_forest.fit(train_inputs, train_targets)

train_preds_rforest = model_random_forest.predict(train_inputs)
test_preds_rforest = model_random_forest.predict(test_inputs)

train_acc = accuracy_score(train_targets, train_preds_rforest)

test_acc, recall_test, precision_test = calculate_basic_metrics(test_targets, test_preds_rforest)

print(f"Train Accuracy = {train_acc:.5f}, Test Accuracy = {test_acc:.5f}")
print(f"Recall = {recall_test:.5f}, Precision = {precision_test:.5f}")

#model_random_forest.estimators_

model_random_forest.get_params()

importance_df = pd.DataFrame({
    "feature": train_inputs.columns,
    "importance": model_random_forest.feature_importances_
}).sort_values("importance", ascending = False)

importance_df.head(15)

sns.barplot(data = importance_df.head(15), x = "importance", y = "feature",
            hue = "feature", legend = False, palette = "tab10")

plt.title("Feature Importance of the Decision Tree");

## Without Data Resampling
# Train Accuracy = 1.0, Test Accuracy = 0.89687
# Recall = 0.24282, Precision = 0.59583

## SMOTE Data Resampling
# Train Accuracy = 1.00000, Test Accuracy = 0.89590
# Recall = 0.90316, Precision = 0.88792

"""## 9. Gradient Boosting Model"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# from xgboost import XGBClassifier
# 
# xgboost_model = XGBClassifier(max_depth = 10,                # 6-10
#                               min_child_weight = 5,          # 2, 5
#                               #gamma = 0,
#                               n_estimators = 1000,
#                               n_jobs = -1,
#                               subsample = 1,                # 1, 0.93
#                               #colsample_bytree = 1,
#                               learning_rate = 0.1,           # 0.3-0.4
#                               random_state = 42,
#                               objective = "reg:squarederror",)      #reg:squarederror
# 
# xgboost_model.fit(train_inputs, train_targets)
# 
# train_preds_xgb = xgboost_model.predict(train_inputs)
# test_preds_xgb = xgboost_model.predict(test_inputs)

train_acc = accuracy_score(train_targets, train_preds_xgb)
test_acc, recall_test, precision_test = calculate_basic_metrics(test_targets, test_preds_xgb)

print(f"Train Accuracy = {train_acc:.5f}, Test Accuracy = {test_acc:.5f}")
print(f"Recall = {recall_test:.5}, Precision = {precision_test:.5f}")

## Without Data Resampling
# Train Accuracy = 0.90046, Test Accuracy = 0.90046
# Recall = 0.23450, Precision = 0.59583

## SMOTE Data Resampling
# Train Accuracy = 0.99984, Test Accuracy = 0.89536
# Recall = 0.90967, Precision = 0.8821